#Requires -Version 5.1

<#
.SYNOPSIS
    Deploys the complete Azure Integration Demo infrastructure
    
.DESCRIPTION
    Deploys all Azure resources using Terraform. Uses Managed Identities
    throughout - no secrets required.
    
.EXAMPLE
    .\scripts\deploy-demo.ps1
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$ResourceGroupName = "rg-demo-integration-$(Get-Date -Format 'yyyyMMdd-HHmmss')",
    
    [Parameter(Mandatory = $false)]
    [string]$Location = "Central US",
    
    [Parameter(Mandatory = $false)]
    [string]$EnvironmentName = "dev"
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "`n[$(Get-Date -Format 'HH:mm:ss')] " -NoNewline -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor White
}

function Write-Success {
    param([string]$Message)
    Write-Host "  [OK] " -NoNewline -ForegroundColor Green
    Write-Host $Message -ForegroundColor Gray
}

function Write-Error-Custom {
    param([string]$Message)
    Write-Host "  [ERROR] " -NoNewline -ForegroundColor Red
    Write-Host $Message -ForegroundColor Yellow
}

# Check prerequisites
Write-Step "Checking prerequisites..."

try {
    $azContext = az account show 2>$null | ConvertFrom-Json
    if (-not $azContext) {
        throw "Not logged in"
    }
    Write-Success "Azure CLI authenticated (Subscription: $($azContext.name))"
} catch {
    Write-Error-Custom "Please login: az login"
    exit 1
}

# Check Terraform
$ErrorActionPreference = "SilentlyContinue"
$terraformCmd = Get-Command terraform -ErrorAction SilentlyContinue
if ($terraformCmd) {
    $terraformVersion = terraform version 2>&1 | Select-String -Pattern "Terraform v" | Select-Object -First 1
    Write-Success "Terraform available: $terraformVersion"
} else {
    Write-Error-Custom "Terraform not found. Install from: https://www.terraform.io/downloads"
    exit 1
}
$ErrorActionPreference = "Stop"

# Clean up old demo resource groups (only those belonging to this repo)
Write-Step "Cleaning up old demo resource groups..."

$ErrorActionPreference = "SilentlyContinue"
# Only find resource groups that match the exact pattern for this demo-integration repo
$oldRgs = az group list --query "[?starts_with(name, 'rg-demo-integration-')].{Name:name, Location:location}" --output json 2>$null | ConvertFrom-Json
$ErrorActionPreference = "Stop"

if ($oldRgs -and $oldRgs.Count -gt 0) {
    Write-Host "  Found $($oldRgs.Count) old resource group(s) belonging to demo-integration" -ForegroundColor Gray
    foreach ($oldRg in $oldRgs) {
        if ($oldRg.Name -ne $ResourceGroupName) {
            Write-Host "  -> Deleting: $($oldRg.Name)..." -ForegroundColor Gray -NoNewline
            az group delete --name $oldRg.Name --yes --no-wait 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {
                Write-Host " Done" -ForegroundColor Green
            } else {
                Write-Host " Failed" -ForegroundColor Yellow
            }
        }
    }
    Write-Success "Old demo-integration resource groups cleanup initiated"
} else {
    Write-Success "No old resource groups found"
}

# Initialize Terraform
Write-Step "Initializing Terraform..."

$terraformPath = Join-Path (Split-Path $PSScriptRoot -Parent) "terraform"

Push-Location $terraformPath
try {
    terraform init
    
    if ($LASTEXITCODE -ne 0) {
        Write-Error-Custom "Terraform init failed"
        exit 1
    }
    Write-Success "Terraform initialized"
} finally {
    Pop-Location
}

# Note: Terraform will create the resource group itself
# The resource group name will be generated by Terraform based on the resource_prefix
Write-Step "Terraform will create the resource group automatically"

# Terraform plan
Write-Step "Running Terraform plan..."

Push-Location $terraformPath
try {
    terraform plan `
        -var="location=$Location" `
        -var="environment_name=$EnvironmentName" `
        -out=tfplan `
        -refresh=false
    
    if ($LASTEXITCODE -ne 0) {
        Write-Error-Custom "Terraform plan failed"
        exit 1
    }
    Write-Success "Terraform plan completed"
} finally {
    Pop-Location
}

# Terraform apply
Write-Step "Applying Terraform configuration (this can take 5-10 minutes)..."

Push-Location $terraformPath
try {
    terraform apply -auto-approve tfplan
    
    if ($LASTEXITCODE -ne 0) {
        Write-Error-Custom "Terraform apply failed"
        exit 1
    }
    Write-Success "Terraform apply completed"
} finally {
    Pop-Location
}

# Get Terraform outputs
Write-Step "Retrieving Terraform outputs..."

Push-Location $terraformPath
try {
    $ResourceGroupName = terraform output -raw resource_group_name
    $functionAppName = terraform output -raw function_app_name
    $storageAccountName = terraform output -raw storage_account_name
    $apimServiceName = terraform output -raw apim_service_name
    $logicAppName = terraform output -raw logic_app_name
    
    Write-Success "Resource Group: $ResourceGroupName"
    Write-Success "Function App: $functionAppName"
    Write-Success "Storage Account: $storageAccountName"
    Write-Success "API Management: $apimServiceName"
    Write-Success "Logic App: $logicAppName"
} finally {
    Pop-Location
}

# Verify Function App exists
Write-Step "Verifying Function App resource..."

$ErrorActionPreference = "SilentlyContinue"
$functionAppResource = az resource list --resource-group $ResourceGroupName --query "[?type=='Microsoft.Web/sites'].name" --output tsv 2>&1 | Where-Object { $_ -and $_ -notmatch "Warning" } | Select-Object -First 1
$ErrorActionPreference = "Stop"

if (-not $functionAppResource) {
    Write-Error-Custom "Function App not found in resources. Terraform deployment may have failed."
    exit 1
}

Write-Success "Function App resource verified: $functionAppResource"

# Deploy functions
Write-Step "Deploying Azure Functions..."

$functionsPath = Join-Path (Split-Path $PSScriptRoot -Parent) "functions"

# Check if func CLI is available
$funcCheck = func --version 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "Azure Functions Core Tools not found. Install with: npm install -g azure-functions-core-tools@4"
    exit 1
}

# Deploy functions
Push-Location $functionsPath
try {
    Write-Host "  -> Deploying functions (ZIP size: ~5 KB)..." -ForegroundColor Gray
    Write-Host "     Function App: $functionAppName" -ForegroundColor Gray
    
    # Deploy directly with --no-selfcontained and --powershell
    func azure functionapp publish $functionAppName --no-selfcontained --powershell --force
    
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Functions deployed"
    } else {
        Write-Error-Custom "Function deployment failed"
        exit 1
    }
} finally {
    Pop-Location
}

# Sync function triggers
Write-Step "Synchronizing function triggers..."

$ErrorActionPreference = "SilentlyContinue"
az functionapp function keys list --resource-group $ResourceGroupName --name $functionAppName --function-name HttpIngest 2>&1 | Out-Null
$ErrorActionPreference = "Stop"

# Trigger sync by restarting Function App
Write-Host "  -> Restarting Function App to sync triggers..." -ForegroundColor Gray
az functionapp restart --resource-group $ResourceGroupName --name $functionAppName 2>&1 | Out-Null

if ($LASTEXITCODE -eq 0) {
    Write-Success "Function App restarted (triggers synced)"
} else {
    Write-Host "  Warning: Could not restart Function App (may still be provisioning)" -ForegroundColor Yellow
}

# Save deployment info
$deploymentInfo = @{
    ResourceGroupName = $ResourceGroupName
    FunctionAppName = $functionAppName
    StorageAccountName = $storageAccountName
    ApimServiceName = $apimServiceName
    LogicAppName = $logicAppName
}

$infoPath = Join-Path (Split-Path $PSScriptRoot -Parent) ".deployment-info.json"
$deploymentInfo | ConvertTo-Json | Set-Content $infoPath

Write-Step "Deployment completed successfully!"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Run: .\scripts\simulate-flow.ps1" -ForegroundColor Cyan
Write-Host "  2. Or specify resource group: .\scripts\simulate-flow.ps1 -ResourceGroupName $ResourceGroupName" -ForegroundColor Cyan
Write-Host ""
